[toolchain]
anchor_version = "0.32.1"

[features]
resolution = true
skip-lint = false

[programs.localnet]
daddys_club = "7eT5T7mq1uD9piYJ2rMAzma8iYL7C7CZGPgxsB8DckoB"
demo_issuer = "8wKjGiLvnMTv7oi9PcztmbRv4v63emT2qPPrA8x1fW3z"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "pnpm vitest run"
